server:
  port: 8082
  tomcat:
    threads:
      max: 200
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spike?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 12345678
  redis:
    host: localhost
    port: 6379
    database: 0

rocketmq:
  name-server: localhost:9876

mybatis-plus:
  mapper-locations:
    classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.hm.model.entity
