server:
  port: 8081
  tomcat:
    threads:
      max: 400

spring:
  redis:
    host: localhost
    port: 6379
    database: 0

rocketmq:
  name-server: localhost:9876
  producer:
    group: seckill-producer-group
